[package]
name = "bevy-detective"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = "0.11.2"
pest = "2.0"
pest_derive = "2.0"
rand = "0.8.5"
